name: deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.1

      - name: Setup Beam
        uses: erlef/setup-beam@v1.15.4
        with:
          otp-version: "25.2"
          gleam-version: "0.30.0"
          rebar3-version: "3"
          # elixir-version: "1.14.2"

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
